services:
  - type: worker
    name: es3-session-bot
    runtime: docker
    plan: free
    buildCommand: docker build -t es3-session-bot .
    startCommand: docker run es3-session-bot
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
